### ISSUE TITLE
Does not purchase timeouts

### ISSUE THREAD

**Issue by DevilTink** [joshprewer/PS5Bot#2]
`Attempting purchase at Game
TimeoutError: waiting for selector `mat-input-0` failed: timeout 110000ms exceeded
    at new WaitTask (C:\Users\James\Desktop\PS5Bot-main\node_modules\puppeteer\lib\cjs\puppeteer\common\DOMWorld.js:505:34)
    at DOMWorld.waitForSelectorInPage (C:\Users\James\Desktop\PS5Bot-main\node_modules\puppeteer\lib\cjs\puppeteer\common\DOMWorld.js:416:26)
    at Object.internalHandler.waitFor (C:\Users\James\Desktop\PS5Bot-main\node_modules\puppeteer\lib\cjs\puppeteer\common\QueryHandler.js:31:77)
    at DOMWorld.waitForSelector (C:\Users\James\Desktop\PS5Bot-main\node_modules\puppeteer\lib\cjs\puppeteer\common\DOMWorld.js:312:29)
    at Frame.waitForSelector (C:\Users\James\Desktop\PS5Bot-main\node_modules\puppeteer\lib\cjs\puppeteer\common\FrameManager.js:842:51)
    at Page.waitForSelector (C:\Users\James\Desktop\PS5Bot-main\node_modules\puppeteer\lib\cjs\puppeteer\common\Page.js:1285:33)
    at Object.<anonymous> (C:\Users\Jamees\Desktop\PS5Bot-main\dist\sites\site.js:22:34)
    at Generator.next (<anonymous>)
    at C:\Users\James\Desktop\PS5Bot-main\dist\sites\site.js:8:71
    at new Promise (<anonymous>)
------------- NOT IN STOCK RETRYING PURCHASE -------------`

Experiencing this error, was attempting to make a test purchase for https://www.game.co.uk/en/m/gameware-ps5-play-and-charge-2826646 before leaving bot running however it spits out above error... Any resolution would be appreciated 

Edit - can I suggest checking out your fillForm as well as it doesn't fill the required fields that you use inputFocus() to fill.. Instead it only goes as far as selecting a Title, such as Mr/Mrs etc

**Comment by DevilTink** [comment]
`    const nameId = "mat-input-0";
    await fillForm(nameId, config.personalDetails.firstName, page);`
    Unfortunately this will not input the required information that is inside the .env file have tried numerous things including below:
     
    
    `await fillForm(FirstNameId, config.personalDetails.firstName, page);
const firstnameId = await page.waitForSelector(`mat-input[id='${firstname}']`);`

However it will not fill any information after selecting your Title as described above. I have also changed it to open Chrome Web Dev in my download so I could find at which point it stopped working, which I have now found is the selectors not filling in information.


This is the same issue across all links on game.co.uk


Can you provide a resolution for fixing this?

**Comment by DevilTink** [comment]
nnn
